github:
  api_url: 'https://api.github.com/repos/{owner}/{repo}/statuses/{commit_sha}'
static_analysis:
  root_dir: 'build'
  results_dir: 'static_analysis'
tests_to_run:
  dynamic:
    pytest:
      input_file: 'pytest.xml'
      regex_pattern: '.*(errors="\d") (failures="\d").*(skips="\d").*(tests="\d")'
      message: 'Pytest score'
      multiplier: 100
      percent: True
  static:
    pylint:
      input_file: 'pylint.static'
      regex_pattern: '.*?(\d+.\d+)/10$'
      message: 'Pylint score'
      multiplier: 10
      percent: True
    coverage:
      input_file: 'pytest.static'
      regex_pattern: '.*?(\d+)%'
      message: 'Coverage score'
      multiplier: 1
      percent: True
    radon_cc:
      input_file: 'radon_cc.static'
      regex_pattern: 'Average complexity: .*?(\d+\.*\d*)'
      message: 'Radon Cyclomatic Complexity score'
      multiplier: 1
      percent: False
    line_counter:
      input_file: 'line_counter.static'
      regex_pattern: 'total lines: (\d+)'
      message: 'Line count for main package'
      multiplier: 1
      percent: False
code_build:
  root_url:
    "https://{region}.console.aws.amazon.com/codebuild/home?region={region}#/builds/\
    {project_name}:{build_id}/view/new"
dynamo:
  table_name: 'build-status'
  partition_key_name: 'branch_name'
  sort_key_name: 'build_start_time'
